### ISSUE TITLE
環境構築手順等を記したREADMEの作成

### ISSUE THREAD

**Issue by hikaruYahagi** [Kawatan1927/bingo-game-2025#19]
・プロジェクト概要、環境構築手順等を記したREADMEを作成する(矢作が作成中)

**Comment by hikaruYahagi** [comment]
プロジェクト名について1点確認なのですが、「BINGO-GAME-**2024**」で間違いない？
新年会は2025年開催なので「BINGO-GAME-**2025**」の方が正しい気がするのですが...

どちらが正しいか確認お願いします。

**Comment by Kawatan1927** [comment]
2025が正しいです。
すみません…
